// ===== DATA.JS — Të dhënat GeoJSON për WebGIS Emergjente Kosovë =====
// Burim koordinatash: institucionet_emergjente.geojson (OSM Overpass API)
// Adresat: reverse geocoding Nominatim/OSM — adresa reale rrugësh
// Kapacitetet: vlerë e përafërt sipas madhësisë së komunës

const STATIONS_POLICE = {
  type: "FeatureCollection",
  features: [
    { type:"Feature", properties:{ id:"P01", emri:"Stacioni Policor Nr. 1 — Prishtinë",       adresa:"Rr. Luan Haradinaj, Prishtinë",              tel:"192", kapaciteti:40, automjete:5, statusi:"aktiv", sherbimi:"policia" }, geometry:{ type:"Point", coordinates:[21.1593137, 42.6619664] } },
    { type:"Feature", properties:{ id:"P02", emri:"Stacioni Policor Nr. 2 — Prishtinë",       adresa:"Rr. Qamile Jaka, Prishtinë",                 tel:"192", kapaciteti:35, automjete:4, statusi:"aktiv", sherbimi:"policia" }, geometry:{ type:"Point", coordinates:[21.1676112, 42.659122 ] } },
    { type:"Feature", properties:{ id:"P03", emri:"Stacioni Policor Jugu — Prishtinë",        adresa:"Rr. Jusuf Gërvalla, Prishtinë",              tel:"192", kapaciteti:30, automjete:4, statusi:"aktiv", sherbimi:"policia" }, geometry:{ type:"Point", coordinates:[21.1553191, 42.6475235] } },
    { type:"Feature", properties:{ id:"P04", emri:"Stacioni Policor Veri — Prishtinë",        adresa:"Rr. Toni Bler, Prishtinë",                   tel:"192", kapaciteti:28, automjete:3, statusi:"aktiv", sherbimi:"policia" }, geometry:{ type:"Point", coordinates:[21.1509816, 42.6651432] } },
    { type:"Feature", properties:{ id:"P05", emri:"Stacioni Policor — Pejë",                  adresa:"Rr. Mbretëresha Teutë, Pejë",                tel:"192", kapaciteti:30, automjete:4, statusi:"aktiv", sherbimi:"policia" }, geometry:{ type:"Point", coordinates:[20.2963547, 42.6623983] } },
    { type:"Feature", properties:{ id:"P06", emri:"Policia e Trafikut — Pejë",                adresa:"Rr. Ndue Bytyqi, Pejë",                      tel:"192", kapaciteti:15, automjete:2, statusi:"aktiv", sherbimi:"policia" }, geometry:{ type:"Point", coordinates:[20.298666,  42.664382 ] } },
    { type:"Feature", properties:{ id:"P07", emri:"Stacioni Policor Drenas",                  adresa:"Rr. Fehmi dhe Xhevë Lladrovci, Drenas",      tel:"192", kapaciteti:18, automjete:2, statusi:"aktiv", sherbimi:"policia" }, geometry:{ type:"Point", coordinates:[20.8967347, 42.6252097] } },
    { type:"Feature", properties:{ id:"P08", emri:"Stacioni Policor i Fushë Kosovës",         adresa:"Rr. Hashim Hajdini, Fushë Kosovë",           tel:"192", kapaciteti:20, automjete:3, statusi:"aktiv", sherbimi:"policia" }, geometry:{ type:"Point", coordinates:[21.0850619, 42.6346962] } },
    { type:"Feature", properties:{ id:"P09", emri:"Stacioni Policor Klinë",                   adresa:"Rr. Sadik Rama, Përlinë",                    tel:"192", kapaciteti:18, automjete:2, statusi:"aktiv", sherbimi:"policia" }, geometry:{ type:"Point", coordinates:[20.5758724, 42.6094587] } },
    { type:"Feature", properties:{ id:"P10", emri:"Nënstacioni Policor Ratkoc",               adresa:"Rr. Safet Latifi, Ratkoc",                   tel:"192", kapaciteti:8,  automjete:1, statusi:"aktiv", sherbimi:"policia" }, geometry:{ type:"Point", coordinates:[20.5381686, 42.4112346] } },
    { type:"Feature", properties:{ id:"P11", emri:"Stacioni Policor — Prizren Qendër",        adresa:"Rr. Viliam Vokeri, Prizren",                 tel:"192", kapaciteti:35, automjete:4, statusi:"aktiv", sherbimi:"policia" }, geometry:{ type:"Point", coordinates:[20.7302141, 42.2103402] } },
    { type:"Feature", properties:{ id:"P12", emri:"Stacioni Policor Prizren (Veri)",          adresa:"Rr. Kalaja e Shkupit, Lubizhdë",             tel:"192", kapaciteti:25, automjete:3, statusi:"aktiv", sherbimi:"policia" }, geometry:{ type:"Point", coordinates:[20.7698957, 42.2489911] } },
    { type:"Feature", properties:{ id:"P13", emri:"Stacioni Policor Rahovec",                 adresa:"Rr. Sheh Mihedini nr.158, Rahovec",          tel:"192", kapaciteti:15, automjete:2, statusi:"aktiv", sherbimi:"policia" }, geometry:{ type:"Point", coordinates:[20.6576926, 42.3969835] } },
    { type:"Feature", properties:{ id:"P14", emri:"Stacioni Policor Gjakovë Qendër",          adresa:"Rr. Skënderbeu nr.237, Gjakovë",             tel:"192", kapaciteti:28, automjete:3, statusi:"aktiv", sherbimi:"policia" }, geometry:{ type:"Point", coordinates:[20.441064,  42.37601  ] } },
    { type:"Feature", properties:{ id:"P15", emri:"Stacioni Policor Skenderaj",               adresa:"Rr. 28 Nëntori nr.166, Skënderaj",           tel:"192", kapaciteti:18, automjete:2, statusi:"aktiv", sherbimi:"policia" }, geometry:{ type:"Point", coordinates:[20.7888974, 42.7443433] } },
    { type:"Feature", properties:{ id:"P16", emri:"Stacioni Policor Leposaviq",               adresa:"Rr. Vukašin Vukašinović, Leposaviq",         tel:"192", kapaciteti:12, automjete:2, statusi:"aktiv", sherbimi:"policia" }, geometry:{ type:"Point", coordinates:[20.800083,  43.1049251] } },
    { type:"Feature", properties:{ id:"P17", emri:"Nënstacioni Policor Zheger",               adresa:"Rr. Milazim Idrizi, Zhegër",                 tel:"192", kapaciteti:8,  automjete:1, statusi:"aktiv", sherbimi:"policia" }, geometry:{ type:"Point", coordinates:[21.485301,  42.3734364] } },
    { type:"Feature", properties:{ id:"P18", emri:"Stacioni Policor Junik",                   adresa:"Rr. Shkelzen Gacaferi, Junik",               tel:"192", kapaciteti:10, automjete:1, statusi:"aktiv", sherbimi:"policia" }, geometry:{ type:"Point", coordinates:[20.2758209, 42.4763662] } },
    { type:"Feature", properties:{ id:"P19", emri:"Stacioni Policor Kufitar — Çakor",         adresa:"Rr. Rozhaja, Radac",                         tel:"192", kapaciteti:15, automjete:2, statusi:"aktiv", sherbimi:"policia" }, geometry:{ type:"Point", coordinates:[20.2886116, 42.7587361] } },
    { type:"Feature", properties:{ id:"P20", emri:"Stacioni Policor Istog",                   adresa:"Rr. Fadil Ferati, Istog",                    tel:"192", kapaciteti:15, automjete:2, statusi:"aktiv", sherbimi:"policia" }, geometry:{ type:"Point", coordinates:[20.4902125, 42.7815665] } },
    { type:"Feature", properties:{ id:"P21", emri:"Stacioni Policor Dragash",                 adresa:"Rr. Hysein Kutlu, Dragash",                  tel:"192", kapaciteti:14, automjete:2, statusi:"aktiv", sherbimi:"policia" }, geometry:{ type:"Point", coordinates:[20.6531816, 42.0608567] } },
    { type:"Feature", properties:{ id:"P22", emri:"Stacioni Policor Shtërpcë",                adresa:"Rr. Devet Jugovića, Shtërpcë",               tel:"192", kapaciteti:10, automjete:1, statusi:"aktiv", sherbimi:"policia" }, geometry:{ type:"Point", coordinates:[21.0232563, 42.2377602] } },
    { type:"Feature", properties:{ id:"P23", emri:"Stacioni Policor Suharekë",                adresa:"Rr. Brigada 123 nr.171, Suharekë",           tel:"192", kapaciteti:16, automjete:2, statusi:"aktiv", sherbimi:"policia" }, geometry:{ type:"Point", coordinates:[20.8320318, 42.3621704] } },
    { type:"Feature", properties:{ id:"P24", emri:"Stacioni Policor Gjilan",                  adresa:"Rr. Mulla Idrizi, Gjilan",                   tel:"192", kapaciteti:32, automjete:4, statusi:"aktiv", sherbimi:"policia" }, geometry:{ type:"Point", coordinates:[21.4702195, 42.4628422] } },
    { type:"Feature", properties:{ id:"P25", emri:"Vendkalimi Kufitar KAPI",                  adresa:"Rr. R-216, Komuna e Kamenicës",              tel:"192", kapaciteti:18, automjete:2, statusi:"aktiv", sherbimi:"policia" }, geometry:{ type:"Point", coordinates:[21.5564959, 42.7352546] } },
    { type:"Feature", properties:{ id:"P26", emri:"Stacioni Policor Kamenicë",                adresa:"Rr. Sylë Zarbinca, Kamenicë",                tel:"192", kapaciteti:20, automjete:3, statusi:"aktiv", sherbimi:"policia" }, geometry:{ type:"Point", coordinates:[21.577466,  42.579512 ] } },
    { type:"Feature", properties:{ id:"P27", emri:"Stacioni Policor Obiliq",                  adresa:"Rr. Adem Jashari, Obiliq",                   tel:"192", kapaciteti:14, automjete:2, statusi:"aktiv", sherbimi:"policia" }, geometry:{ type:"Point", coordinates:[21.0695785, 42.6867555] } },
    { type:"Feature", properties:{ id:"P28", emri:"Stacioni Policor Vushtrri",                adresa:"Rr. Çamëria, Vushtrri",                      tel:"192", kapaciteti:22, automjete:3, statusi:"aktiv", sherbimi:"policia" }, geometry:{ type:"Point", coordinates:[20.9654388, 42.8251129] } },
    { type:"Feature", properties:{ id:"P29", emri:"Stacioni Policor Zveçan",                  adresa:"Rr. Nikole Tesle, Zveçan",                   tel:"192", kapaciteti:10, automjete:1, statusi:"aktiv", sherbimi:"policia" }, geometry:{ type:"Point", coordinates:[20.8405231, 42.9060521] } },
    { type:"Feature", properties:{ id:"P30", emri:"Stacioni Policor Orllan",                  adresa:"Rr. Mehmet Hoxha, Orllan",                   tel:"192", kapaciteti:12, automjete:2, statusi:"aktiv", sherbimi:"policia" }, geometry:{ type:"Point", coordinates:[21.3382474, 42.8168824] } },
    { type:"Feature", properties:{ id:"P31", emri:"Drejtoria Rajonale Kufitare — Veri",       adresa:"Rr. Vëllezërit Bunjaku, Lluzhanë",           tel:"192", kapaciteti:30, automjete:4, statusi:"aktiv", sherbimi:"policia" }, geometry:{ type:"Point", coordinates:[21.1678775, 42.823476 ] } },
    { type:"Feature", properties:{ id:"P32", emri:"Stacioni Policor Podujevë",                adresa:"Rr. Nuhi Gashi, Podujevë",                   tel:"192", kapaciteti:22, automjete:3, statusi:"aktiv", sherbimi:"policia" }, geometry:{ type:"Point", coordinates:[21.1919163, 42.91163  ] } },
    { type:"Feature", properties:{ id:"P33", emri:"Vendkalimi Kufitar Merdarë",               adresa:"Rr. Gryka e Llapit, Merdar",                 tel:"192", kapaciteti:20, automjete:2, statusi:"aktiv", sherbimi:"policia" }, geometry:{ type:"Point", coordinates:[21.2427241, 42.9369978] } },
    { type:"Feature", properties:{ id:"P34", emri:"Vendkalimi Kufitar Dheu i Bardhë",         adresa:"Rr. Bujanoc, Kormnjan i Poshtëm",            tel:"192", kapaciteti:16, automjete:2, statusi:"aktiv", sherbimi:"policia" }, geometry:{ type:"Point", coordinates:[21.6416003, 42.5062746] } },
    { type:"Feature", properties:{ id:"P35", emri:"Stacioni Policor Muçivërc",                adresa:"Rr. Veteranët e UÇK-së nr.17, Muçivërc",     tel:"192", kapaciteti:10, automjete:1, statusi:"aktiv", sherbimi:"policia" }, geometry:{ type:"Point", coordinates:[21.65841,   42.5597547] } },
    { type:"Feature", properties:{ id:"P36", emri:"Stacioni Policor-Mitrovicë",               adresa:"Rr. Marie Shllaku, Mitrovicë",               tel:"192", kapaciteti:30, automjete:4, statusi:"aktiv", sherbimi:"policia" }, geometry:{ type:"Point", coordinates:[20.8742914, 42.8906698] } },
    { type:"Feature", properties:{ id:"P37", emri:"Stacioni policor-Viti",                    adresa:"Rr. Adem Jashari nr.26, Viti",               tel:"192", kapaciteti:16, automjete:2, statusi:"aktiv", sherbimi:"policia" }, geometry:{ type:"Point", coordinates:[21.3556789, 42.3207967] } },
  ]
};

const STATIONS_FIRE = {
  type: "FeatureCollection",
  features: [
    { type:"Feature", properties:{ id:"Z01", emri:"Stacioni i Zjarrfikësve Kamenicë",         adresa:"Rr. Tahir Sinani, Kamenicë",                 tel:"193", kapaciteti:8,  automjete:2, statusi:"aktiv", sherbimi:"zjarrfikes" }, geometry:{ type:"Point", coordinates:[21.5799898, 42.5822489] } },
    { type:"Feature", properties:{ id:"Z02", emri:"Stacioni i Zjarrfikësve Gjakovë",          adresa:"Rr. Gjergj Sokoli, Gjakovë",                 tel:"193", kapaciteti:12, automjete:3, statusi:"aktiv", sherbimi:"zjarrfikes" }, geometry:{ type:"Point", coordinates:[20.4250515, 42.391822 ] } },
    { type:"Feature", properties:{ id:"Z03", emri:"Brigada e Zjarrfikësve Klinë",             adresa:"Rr. Hasan Prishtina, Klinë",                 tel:"193", kapaciteti:8,  automjete:2, statusi:"aktiv", sherbimi:"zjarrfikes" }, geometry:{ type:"Point", coordinates:[20.5747172, 42.6152313] } },
    { type:"Feature", properties:{ id:"Z04", emri:"Stacioni i Zjarrfikësve Zhur",             adresa:"Rr. Luma e Kuqe, Zhur",                      tel:"193", kapaciteti:6,  automjete:2, statusi:"aktiv", sherbimi:"zjarrfikes" }, geometry:{ type:"Point", coordinates:[20.6153613, 42.1678942] } },
    { type:"Feature", properties:{ id:"Z05", emri:"Stacioni i Zjarrfikësve (Prizren Jug)",    adresa:"Rr. Arsimi, Gjonaj",                         tel:"193", kapaciteti:10, automjete:3, statusi:"aktiv", sherbimi:"zjarrfikes" }, geometry:{ type:"Point", coordinates:[20.6259221, 42.2556074] } },
    { type:"Feature", properties:{ id:"Z06", emri:"Stacioni i Zjarrfikësve Podujevë",         adresa:"Rr. Ramë Govori, Podujevë",                  tel:"193", kapaciteti:8,  automjete:2, statusi:"aktiv", sherbimi:"zjarrfikes" }, geometry:{ type:"Point", coordinates:[21.1902,    42.9168353] } },
    { type:"Feature", properties:{ id:"Z07", emri:"Brigada e Zjarrfikësve Pejë",              adresa:"Rr. Xhem Sadrija, Pejë",                     tel:"193", kapaciteti:12, automjete:3, statusi:"aktiv", sherbimi:"zjarrfikes" }, geometry:{ type:"Point", coordinates:[20.3209693, 42.6551882] } },
    { type:"Feature", properties:{ id:"Z08", emri:"Stacioni i Zjarrfikësve Skenderaj",        adresa:"Rr. Ali Gashi nr.168, Novosellë",            tel:"193", kapaciteti:7,  automjete:2, statusi:"aktiv", sherbimi:"zjarrfikes" }, geometry:{ type:"Point", coordinates:[20.7974232, 42.7363692] } },
    { type:"Feature", properties:{ id:"Z09", emri:"Stacioni i Zjarrfikësve Prizren",          adresa:"Rr. Ibrahim Lutfiu, Prizren",                tel:"193", kapaciteti:12, automjete:3, statusi:"aktiv", sherbimi:"zjarrfikes" }, geometry:{ type:"Point", coordinates:[20.7298156, 42.2102001] } },
    { type:"Feature", properties:{ id:"Z10", emri:"Stacioni i zjarrëfikësve-Ferizaj",         adresa:"Rr. Brigada 161 nr.23, Ferizaj",             tel:"193", kapaciteti:10, automjete:3, statusi:"aktiv", sherbimi:"zjarrfikes" }, geometry:{ type:"Point", coordinates:[21.1477396, 42.3754035] } },
    { type:"Feature", properties:{ id:"Z11", emri:"Stacioni i Zjarrëfikësve-Prishtinë",       adresa:"Rr. Tahir Zajmi, Prishtinë",                 tel:"193", kapaciteti:16, automjete:4, statusi:"aktiv", sherbimi:"zjarrfikes" }, geometry:{ type:"Point", coordinates:[21.1436800, 42.6499066] } },
    { type:"Feature", properties:{ id:"Z12", emri:"Stacioni i Zjarrëfikësve-Mitrovicë",       adresa:"Rr. Driton M. Veliu nr.13, Mitrovicë",       tel:"193", kapaciteti:10, automjete:3, statusi:"aktiv", sherbimi:"zjarrfikes" }, geometry:{ type:"Point", coordinates:[20.8543397, 42.8799615] } },
    { type:"Feature", properties:{ id:"Z13", emri:"Stacioni i Zjarrëfikësve-Gjilan",          adresa:"Rr. Isa Boletini, Gjilan",                   tel:"193", kapaciteti:10, automjete:3, statusi:"aktiv", sherbimi:"zjarrfikes" }, geometry:{ type:"Point", coordinates:[21.4668517, 42.4581795] } },
    { type:"Feature", properties:{ id:"Z14", emri:"Stacioni i Zjarrëfikësve-Kaqanik",         adresa:"Rr. Hamzë Jashari nr.99, Kaçanik",           tel:"193", kapaciteti:6,  automjete:2, statusi:"aktiv", sherbimi:"zjarrfikes" }, geometry:{ type:"Point", coordinates:[21.2415992, 42.2411035] } },
  ]
};

const STATIONS_AMB = {
  type: "FeatureCollection",
  features: [
    { type:"Feature", properties:{ id:"A01", emri:"QKMF Kamenicë",                                          adresa:"Rr. Ismail Ismajli, Kamenicë",               tel:"194", ambulancat:3, statusi:"aktiv", sherbimi:"ambulance" }, geometry:{ type:"Point", coordinates:[21.580115,  42.5763475] } },
    { type:"Feature", properties:{ id:"A02", emri:"Qendra e Mjekësisë Familjare — Prishtinë",               adresa:"Rr. Gjergj Fishta, Prishtinë",               tel:"194", ambulancat:6, statusi:"aktiv", sherbimi:"ambulance" }, geometry:{ type:"Point", coordinates:[21.165047,  42.6705506] } },
    { type:"Feature", properties:{ id:"A03", emri:"QMF Dardani — Prishtinë",                                adresa:"Rr. Shëndeti, Prishtinë",                    tel:"194", ambulancat:4, statusi:"aktiv", sherbimi:"ambulance" }, geometry:{ type:"Point", coordinates:[21.1575312, 42.6526257] } },
    { type:"Feature", properties:{ id:"A04", emri:"Qendra e Mjekësisë Familjare — Pejë",                    adresa:"Rr. Bajram Kelmendi, Pejë",                  tel:"194", ambulancat:4, statusi:"aktiv", sherbimi:"ambulance" }, geometry:{ type:"Point", coordinates:[20.2834918, 42.6605649] } },
    { type:"Feature", properties:{ id:"A05", emri:"QMF Tusuz — Prizren",                                    adresa:"Rr. Shefqet Berisha, Prizren",               tel:"194", ambulancat:3, statusi:"aktiv", sherbimi:"ambulance" }, geometry:{ type:"Point", coordinates:[20.7142713, 42.2002468] } },
    { type:"Feature", properties:{ id:"A06", emri:"Qendra Mjekësore — Prizren",                             adresa:"Rr. Gani Saramati, Prizren",                 tel:"194", ambulancat:4, statusi:"aktiv", sherbimi:"ambulance" }, geometry:{ type:"Point", coordinates:[20.7415273, 42.2247049] } },
    { type:"Feature", properties:{ id:"A07", emri:"QKMF I — Prishtinë (Lagja Arbëri)",                      adresa:"Rr. Ilir Konushevci, Prishtinë",             tel:"194", ambulancat:5, statusi:"aktiv", sherbimi:"ambulance" }, geometry:{ type:"Point", coordinates:[21.164088,  42.6681111] } },
    { type:"Feature", properties:{ id:"A08", emri:"AMF Guska / Nr.03 — Gjakovë",                            adresa:"Rr. Mikel Pepaj, Gjakovë",                   tel:"194", ambulancat:2, statusi:"aktiv", sherbimi:"ambulance" }, geometry:{ type:"Point", coordinates:[20.3921906, 42.3624504] } },
    { type:"Feature", properties:{ id:"A09", emri:"AMF Mulliq / Nr.06 — Deçan/Junik",                       adresa:"Rr. Dëshmorët e Molliqit, Molliq",           tel:"194", ambulancat:2, statusi:"aktiv", sherbimi:"ambulance" }, geometry:{ type:"Point", coordinates:[20.2675984, 42.4365188] } },
    { type:"Feature", properties:{ id:"A10", emri:"AMF Bec / Nr.07 — Istog",                                adresa:"Rr. Beat Coli, Bec",                         tel:"194", ambulancat:2, statusi:"aktiv", sherbimi:"ambulance" }, geometry:{ type:"Point", coordinates:[20.4483588, 42.4418743] } },
    { type:"Feature", properties:{ id:"A11", emri:"AMF Gërgoc / Nr.09 — Istog",                             adresa:"Rr. Fazli e Kamer Nimani, Gërgoc",           tel:"194", ambulancat:1, statusi:"aktiv", sherbimi:"ambulance" }, geometry:{ type:"Point", coordinates:[20.4557605, 42.5092436] } },
    { type:"Feature", properties:{ id:"A12", emri:"AMF Shqiponjë / Nr.11 — Istog",                          adresa:"Rr. Rrezistenca 1993, Shqiponjë",            tel:"194", ambulancat:1, statusi:"aktiv", sherbimi:"ambulance" }, geometry:{ type:"Point", coordinates:[20.4806527, 42.5431021] } },
    { type:"Feature", properties:{ id:"A13", emri:"AMF Blinisht / Nr.14 — Gjakovë",                         adresa:"Rr. Shaban Lushaj, Gjakovë",                 tel:"194", ambulancat:1, statusi:"aktiv", sherbimi:"ambulance" }, geometry:{ type:"Point", coordinates:[20.478138,  42.3119954] } },
    { type:"Feature", properties:{ id:"A14", emri:"AMF Bistrazhin / Nr.15 — Gjakovë",                       adresa:"Rr. Ernest Koliqi, Bishtazhin",              tel:"194", ambulancat:2, statusi:"aktiv", sherbimi:"ambulance" }, geometry:{ type:"Point", coordinates:[20.5144636, 42.3591964] } },
    { type:"Feature", properties:{ id:"A15", emri:"AMF Demjan / Nr.16 — Dragash",                           adresa:"Rr. Hamëz Fetahu, Demjan",                   tel:"194", ambulancat:1, statusi:"aktiv", sherbimi:"ambulance" }, geometry:{ type:"Point", coordinates:[20.5223808, 42.2969855] } },
    { type:"Feature", properties:{ id:"A16", emri:"Ambulanta — Zubin Potok",                                adresa:"Rr. Dëshmorët e Prekazit, Prekaz i Epërm",  tel:"194", ambulancat:1, statusi:"aktiv", sherbimi:"ambulance" }, geometry:{ type:"Point", coordinates:[20.8337313, 42.7746653] } },
    { type:"Feature", properties:{ id:"A17", emri:"QMF Komoran — Drenas",                                   adresa:"Rr. Shpetim Robaj, Drenas",                  tel:"194", ambulancat:2, statusi:"aktiv", sherbimi:"ambulance" }, geometry:{ type:"Point", coordinates:[20.8989745, 42.5752273] } },
    { type:"Feature", properties:{ id:"A18", emri:"Ambulanta Familjare — Mitrovicë Jug",                    adresa:"Rr. Abedin Xhaka, Oshlan",                   tel:"194", ambulancat:2, statusi:"aktiv", sherbimi:"ambulance" }, geometry:{ type:"Point", coordinates:[20.8702261, 42.8078419] } },
    { type:"Feature", properties:{ id:"A19", emri:"Ambulanca e Çabrës — Zubin Potok",                       adresa:"Rr. Behram Jakupi, Çabër",                   tel:"194", ambulancat:1, statusi:"aktiv", sherbimi:"ambulance" }, geometry:{ type:"Point", coordinates:[20.7790063, 42.9019375] } },
    { type:"Feature", properties:{ id:"A20", emri:"Qendra e Mjekësisë Familjare Barë — Vushtrri Veri",      adresa:"Rr. Brigada 141 Mehë Uka, Bajgorë",          tel:"194", ambulancat:2, statusi:"aktiv", sherbimi:"ambulance" }, geometry:{ type:"Point", coordinates:[20.9655488, 42.9518026] } },
    { type:"Feature", properties:{ id:"A21", emri:"Qendra e Mjekësisë Familjare — Pejë Qendër",             adresa:"Rr. Vëllazeria Tabaku, Pejë",                tel:"194", ambulancat:4, statusi:"aktiv", sherbimi:"ambulance" }, geometry:{ type:"Point", coordinates:[20.2986404, 42.6567357] } },
    { type:"Feature", properties:{ id:"A22", emri:"Dom Zdravlja Donja Gusterica — Lipjan",                  adresa:"Rr. Majke Jevrosime, Gushtericë e Poshtme", tel:"194", ambulancat:2, statusi:"aktiv", sherbimi:"ambulance" }, geometry:{ type:"Point", coordinates:[21.1782112, 42.5449135] } },
    { type:"Feature", properties:{ id:"A23", emri:"Dom Zdravlja — Leposaviq",                               adresa:"Rr. Vuk Karadžić, Soçanicë",                 tel:"194", ambulancat:2, statusi:"aktiv", sherbimi:"ambulance" }, geometry:{ type:"Point", coordinates:[20.8092758, 43.0537864] } },
    { type:"Feature", properties:{ id:"A24", emri:"Qendra Shëndetësore — Zubin Potok",                      adresa:"Rr. 18 Qershori, Skënderaj",                 tel:"194", ambulancat:2, statusi:"aktiv", sherbimi:"ambulance" }, geometry:{ type:"Point", coordinates:[20.7877544, 42.7476495] } },
    { type:"Feature", properties:{ id:"A25", emri:"AMF Vragoli — Fushë Kosovë",                             adresa:"Rr. Mëhalla e Lartë nr.91, Vragoli",         tel:"194", ambulancat:2, statusi:"aktiv", sherbimi:"ambulance" }, geometry:{ type:"Point", coordinates:[21.0566551, 42.6112226] } },
    { type:"Feature", properties:{ id:"A26", emri:"QMF — Drenas Veri",                                      adresa:"Rr. Hamit Bylykbashi nr.2, Drenas",          tel:"194", ambulancat:1, statusi:"aktiv", sherbimi:"ambulance" }, geometry:{ type:"Point", coordinates:[20.8471753, 42.6642557] } },
    { type:"Feature", properties:{ id:"A27", emri:"QMF Kaçaniku i Vjetër",                                  adresa:"Rr. Komandant Bardhi, Kaçanik i Vjetër",    tel:"194", ambulancat:2, statusi:"aktiv", sherbimi:"ambulance" }, geometry:{ type:"Point", coordinates:[21.2291821, 42.2993489] } },
    { type:"Feature", properties:{ id:"A28", emri:"Poliklinika Diagnostika — Istog",                        adresa:"Rr. Ibrahim Rugova nr.73, Istog",            tel:"194", ambulancat:2, statusi:"aktiv", sherbimi:"ambulance" }, geometry:{ type:"Point", coordinates:[20.4873238, 42.7800077] } },
    { type:"Feature", properties:{ id:"A29", emri:"AMF — Klinë (Lagja)",                                    adresa:"Rr. Zene Veseli nr.48, Açarevë",             tel:"194", ambulancat:1, statusi:"aktiv", sherbimi:"ambulance" }, geometry:{ type:"Point", coordinates:[20.7169585, 42.6500855] } },
    { type:"Feature", properties:{ id:"A30", emri:"AMF Kuki — Dragash",                                     adresa:"Rr. Demokracia, Kuk",                        tel:"194", ambulancat:1, statusi:"aktiv", sherbimi:"ambulance" }, geometry:{ type:"Point", coordinates:[20.7134932, 42.1007367] } },
    { type:"Feature", properties:{ id:"A31", emri:"AMF — Vushtrri (Fshat)",                                 adresa:"Rr. Bislim Shaqiri, Pantinë",                tel:"194", ambulancat:1, statusi:"aktiv", sherbimi:"ambulance" }, geometry:{ type:"Point", coordinates:[20.9185695, 42.8357821] } },
    { type:"Feature", properties:{ id:"A32", emri:"AMF Bob — Kaçanik",                                      adresa:"Rr. Vëllezërit Çaka, Bob",                   tel:"194", ambulancat:1, statusi:"aktiv", sherbimi:"ambulance" }, geometry:{ type:"Point", coordinates:[21.2487897, 42.2305093] } },
    { type:"Feature", properties:{ id:"A33", emri:"AMF Dobrushtë — Dragash",                                adresa:"Rr. Ramë Maksuti, Dobrushtë",                tel:"194", ambulancat:1, statusi:"aktiv", sherbimi:"ambulance" }, geometry:{ type:"Point", coordinates:[20.5904442, 42.1808649] } },
    { type:"Feature", properties:{ id:"A34", emri:"AMF — Prizren Jug/Dragash",                              adresa:"Rr. Tafë Zeneli, Lubizhdë e Hasit",          tel:"194", ambulancat:1, statusi:"aktiv", sherbimi:"ambulance" }, geometry:{ type:"Point", coordinates:[20.5753514, 42.2558599] } },
    { type:"Feature", properties:{ id:"A35", emri:"AMF Dabishec — Podujevë",                                adresa:"Rr. Dushkaja, Dabishec",                     tel:"194", ambulancat:2, statusi:"aktiv", sherbimi:"ambulance" }, geometry:{ type:"Point", coordinates:[21.4408306, 42.735048 ] } },
    { type:"Feature", properties:{ id:"A36", emri:"AMF Kraishta — Lipjan",                                  adresa:"Rr. Banush Kodra, Kraishtë",                 tel:"194", ambulancat:1, statusi:"aktiv", sherbimi:"ambulance" }, geometry:{ type:"Point", coordinates:[21.050141,  42.4983015] } },
    { type:"Feature", properties:{ id:"A37", emri:"AMF — Malishevë (Fshat)",                                adresa:"Rr. Skënder Bytyçi, Nishor",                 tel:"194", ambulancat:1, statusi:"aktiv", sherbimi:"ambulance" }, geometry:{ type:"Point", coordinates:[20.8023307, 42.4195381] } },
    { type:"Feature", properties:{ id:"A38", emri:"AMF — Kaçanik/Shtime",                                   adresa:"Rr. Bau Bajden, Dardani",                    tel:"194", ambulancat:1, statusi:"aktiv", sherbimi:"ambulance" }, geometry:{ type:"Point", coordinates:[21.2760571, 42.3777125] } },
    { type:"Feature", properties:{ id:"A39", emri:"AMF Barilevë — Podujevë",                                adresa:"Rr. Ahmet Shala, Barilevë",                  tel:"194", ambulancat:2, statusi:"aktiv", sherbimi:"ambulance" }, geometry:{ type:"Point", coordinates:[21.1108913, 42.7534244] } },
    { type:"Feature", properties:{ id:"A40", emri:"QMF Bellobradi — Dragash",                               adresa:"Rr. Dielli, Brrut",                          tel:"194", ambulancat:1, statusi:"aktiv", sherbimi:"ambulance" }, geometry:{ type:"Point", coordinates:[20.6884065, 42.1193428] } },
    { type:"Feature", properties:{ id:"A41", emri:"QMF Rizniqi — Deçan",                                    adresa:"Rr. Altin Haskaj, Irzniq",                   tel:"194", ambulancat:2, statusi:"aktiv", sherbimi:"ambulance" }, geometry:{ type:"Point", coordinates:[20.3497764, 42.5206026] } },
    { type:"Feature", properties:{ id:"A42", emri:"QMF Ujëmir — Klinë",                                     adresa:"Rr. Adem Jashari, Ujë Mirë",                 tel:"194", ambulancat:2, statusi:"aktiv", sherbimi:"ambulance" }, geometry:{ type:"Point", coordinates:[20.697282,  42.6147675] } },
    { type:"Feature", properties:{ id:"A43", emri:"AMF Obranqe — Podujevë",                                 adresa:"Rr. Azem Jashari, Obrançë",                  tel:"194", ambulancat:1, statusi:"aktiv", sherbimi:"ambulance" }, geometry:{ type:"Point", coordinates:[21.1706988, 42.9154586] } },
    { type:"Feature", properties:{ id:"A44", emri:"QKMF Korishë — Prizren",                                 adresa:"Rr. Sadri Kabashi, Korishë",                 tel:"194", ambulancat:2, statusi:"aktiv", sherbimi:"ambulance" }, geometry:{ type:"Point", coordinates:[20.7943736, 42.2577969] } },
    { type:"Feature", properties:{ id:"A45", emri:"Qendra Shëndetësore — Malishevë",                        adresa:"Rr. Komuna, Duhël",                          tel:"194", ambulancat:2, statusi:"aktiv", sherbimi:"ambulance" }, geometry:{ type:"Point", coordinates:[20.8712828, 42.4092555] } },
    { type:"Feature", properties:{ id:"A46", emri:"Qendra e Mjekësisë Familjare — Suharekë",                adresa:"Rr. Xhemajli Halimi, Samadrexhë",            tel:"194", ambulancat:3, statusi:"aktiv", sherbimi:"ambulance" }, geometry:{ type:"Point", coordinates:[20.7426278, 42.3660569] } },
    { type:"Feature", properties:{ id:"A47", emri:"QMF — Deçan (Veri)",                                     adresa:"Rr. Dëshmorët e Raushiqit, Raushiq",         tel:"194", ambulancat:2, statusi:"aktiv", sherbimi:"ambulance" }, geometry:{ type:"Point", coordinates:[20.3047689, 42.6167218] } },
    { type:"Feature", properties:{ id:"A48", emri:"AMF Fushë Kosovë 2",                                     adresa:"Rr. Kuvendi i Lezhes, Fushë Kosovë",         tel:"194", ambulancat:2, statusi:"aktiv", sherbimi:"ambulance" }, geometry:{ type:"Point", coordinates:[21.0965295, 42.6419963] } },
    { type:"Feature", properties:{ id:"A49", emri:"QKMF Kryesore — Gjilan",                                 adresa:"Rr. Ibrahim Rugova, Gjilan",                 tel:"194", ambulancat:5, statusi:"aktiv", sherbimi:"ambulance" }, geometry:{ type:"Point", coordinates:[21.4657071, 42.4585843] } },
    { type:"Feature", properties:{ id:"A50", emri:"AMF Qendra e Studentëve — Prishtinë",                    adresa:"Rr. Edmond Hoxha, Prishtinë",                tel:"194", ambulancat:3, statusi:"aktiv", sherbimi:"ambulance" }, geometry:{ type:"Point", coordinates:[21.1653401, 42.65438  ] } },
    { type:"Feature", properties:{ id:"A51", emri:"Qendra e Mjekësisë Familjare Sllatinë — Obiliq",         adresa:"Rr. Magurë, Sllatinë e Madhe",               tel:"194", ambulancat:2, statusi:"aktiv", sherbimi:"ambulance" }, geometry:{ type:"Point", coordinates:[21.0208851, 42.5992204] } },
    { type:"Feature", properties:{ id:"A52", emri:"Qendra e Mjekësisë Familjare Bob — Kaçanik",             adresa:"Rr. Muhamet Zeneli nr.76, Bob",              tel:"194", ambulancat:2, statusi:"aktiv", sherbimi:"ambulance" }, geometry:{ type:"Point", coordinates:[21.2524343, 42.2274016] } },
    { type:"Feature", properties:{ id:"A53", emri:"Qendra Shëndetësore — Podujevë (Lindore)",               adresa:"Rr. Kuçova, Siqevë",                         tel:"194", ambulancat:2, statusi:"aktiv", sherbimi:"ambulance" }, geometry:{ type:"Point", coordinates:[21.1957,    42.7256054] } },
    { type:"Feature", properties:{ id:"A54", emri:"Qendra Shëndetësore — Vushtrri Veri",                    adresa:"Rr. Bujar Krasniqi nr.4, Ceceli",            tel:"194", ambulancat:2, statusi:"aktiv", sherbimi:"ambulance" }, geometry:{ type:"Point", coordinates:[21.0559899, 42.8469771] } },
    { type:"Feature", properties:{ id:"A55", emri:"Ambulanta e Fshatit Breznicë — Podujevë",                adresa:"Rr. Koskoviku nr.15, Breznicë",              tel:"194", ambulancat:1, statusi:"aktiv", sherbimi:"ambulance" }, geometry:{ type:"Point", coordinates:[21.0893764, 42.7778517] } },
    { type:"Feature", properties:{ id:"A56", emri:"Ambulanca Adem Ukehaxhaj — Deçan",                       adresa:"Rr. Dëshmorët e Kombit, Carrabreg i Ulët",  tel:"194", ambulancat:2, statusi:"aktiv", sherbimi:"ambulance" }, geometry:{ type:"Point", coordinates:[20.2945761, 42.5327194] } },
    { type:"Feature", properties:{ id:"A57", emri:"QKMF Kaqanik",                                           adresa:"Rr. Ismail Raka nr.196, Kaçanik",            tel:"194", ambulancat:3, statusi:"aktiv", sherbimi:"ambulance" }, geometry:{ type:"Point", coordinates:[21.2561656, 42.2348630] } },
  ]
};

const HOSPITALS = {
  type: "FeatureCollection",
  features: [
    { type:"Feature", properties:{ id:"H01", emri:"Spitali i Mitrovicës Jugore",                    adresa:"Rr. UÇK, Mitrovicë",                         tel:"028-530-000",  "shtretër":180, ICU:8,  urgjenca:true, statusi:"aktiv", sherbimi:"spital" }, geometry:{ type:"Point", coordinates:[20.873612,  42.8862018] } },
    { type:"Feature", properties:{ id:"H02", emri:"Bolnica Kosovska Mitrovica (Veri)",               adresa:"Rr. Adem Ademi, Mitrovicë Veriore",          tel:"028-535-000",  "shtretër":120, ICU:6,  urgjenca:true, statusi:"aktiv", sherbimi:"spital" }, geometry:{ type:"Point", coordinates:[20.8596024, 42.8922909] } },
    { type:"Feature", properties:{ id:"H03", emri:"Spitali Sheik Zahid — Vushtrri",                 adresa:"Rr. Çamëria, Vushtrri",                      tel:"028-571-000",  "shtretër":100, ICU:6,  urgjenca:true, statusi:"aktiv", sherbimi:"spital" }, geometry:{ type:"Point", coordinates:[20.9644824, 42.8247336] } },
    { type:"Feature", properties:{ id:"H04", emri:"Spitali Rajonal Graçanicë",                      adresa:"Rr. Šaškovačka, Shushicë",                   tel:"038-560-000",  "shtretër":80,  ICU:4,  urgjenca:true, statusi:"aktiv", sherbimi:"spital" }, geometry:{ type:"Point", coordinates:[21.2081857, 42.5836695] } },
    { type:"Feature", properties:{ id:"H05", emri:"Spitali rajonal i Ferizajit",                    adresa:"Rr. Uran Tinova, Ferizaj",                   tel:"0290-320-000", "shtretër":180, ICU:8,  urgjenca:true, statusi:"aktiv", sherbimi:"spital" }, geometry:{ type:"Point", coordinates:[21.1456524, 42.3715065] } },
    { type:"Feature", properties:{ id:"H06", emri:"Spitali rajonal \"Isa Grezda\"-Gjakovë",         adresa:"Rr. Dëshmorët Dervishdana nr.100, Gjakovë",  tel:"0390-323-000", "shtretër":200, ICU:10, urgjenca:true, statusi:"aktiv", sherbimi:"spital" }, geometry:{ type:"Point", coordinates:[20.4296649, 42.3693870] } },
    { type:"Feature", properties:{ id:"H07", emri:"Qendra Klinike Universitare e Kosovës-QKUK",     adresa:"Rr. Qendra Spitalore, Prishtinë",             tel:"038-500-600",  "shtretër":1200,ICU:48, urgjenca:true, statusi:"aktiv", sherbimi:"spital" }, geometry:{ type:"Point", coordinates:[21.1643009, 42.6453139] } },
    { type:"Feature", properties:{ id:"H08", emri:"Spitali regjional i Pejës",                      adresa:"Rr. Nënë Tereza, Pejë",                      tel:"039-430-000",  "shtretër":240, ICU:10, urgjenca:true, statusi:"aktiv", sherbimi:"spital" }, geometry:{ type:"Point", coordinates:[20.2721870, 42.6626255] } },
    { type:"Feature", properties:{ id:"H09", emri:"Spitali regjional i Prizrenit",                  adresa:"Rr. Fadil Rifati, Prizren",                  tel:"029-220-000",  "shtretër":320, ICU:14, urgjenca:true, statusi:"aktiv", sherbimi:"spital" }, geometry:{ type:"Point", coordinates:[20.7301376, 42.2037738] } },
    { type:"Feature", properties:{ id:"H10", emri:"Spitali regjional i Gjilanit",                   adresa:"Rr. Fahri Rashit Gorani, Gjilan",             tel:"0280-320-000", "shtretër":280, ICU:12, urgjenca:true, statusi:"aktiv", sherbimi:"spital" }, geometry:{ type:"Point", coordinates:[21.4628189, 42.4577385] } },
  ]
};

const INCIDENTS = {
  type: "FeatureCollection",
  features: [
    // ── ASHPËRSI E LARTË (HIGH) ──────────────────────────────────────────────────
    { type:"Feature", properties:{ id:"INC001", lloji:"Aksident masiv rrugor", ashpersia:"high", statusi:"aktiv",
        sherbimi:"policia", sherbime:["policia","ambulance","zjarrfikes"],
        koha:"09:47", adresa:"Rr. Ismet Asllani, Rufc i Vjetër",
        pershkrimi:"Kamion përplaset me autobus, 6 të lënduar, bllokadë totale, rrjedhje karburanti",
        njesia:"Patrulla P-08 + Ambulanca A-48 + Brigada Z-11" },
      geometry:{ type:"Point", coordinates:[21.0925, 42.5218] } },

    { type:"Feature", properties:{ id:"INC002", lloji:"Zjarr banesë shumëkatëshe", ashpersia:"high", statusi:"aktiv",
        sherbimi:"zjarrfikes", sherbime:["zjarrfikes","ambulance"],
        koha:"09:32", adresa:"Rr. Butrinti, Prishtinë",
        pershkrimi:"Zjarr në katin e 3-të, tymë i dendur, 2 persona të bllokuar brenda",
        njesia:"Brigada Z-11 + Ambulanca A-07" },
      geometry:{ type:"Point", coordinates:[21.1742, 42.6718] } },

    { type:"Feature", properties:{ id:"INC003", lloji:"Sulm me armë zjarri", ashpersia:"high", statusi:"aktiv",
        sherbimi:"policia", sherbime:["policia","ambulance"],
        koha:"09:18", adresa:"Rr. Isa Boletini, Mitrovicë",
        pershkrimi:"Shkëmbim zjarri, 1 i plagosur rëndë, zona e izoluar, kërkohet njësi TAK",
        njesia:"Patrulla P-36 + Ambulanca A-18" },
      geometry:{ type:"Point", coordinates:[20.8660, 42.8918] } },

    { type:"Feature", properties:{ id:"INC004", lloji:"Zjarr industrial", ashpersia:"high", statusi:"aktiv",
        sherbimi:"zjarrfikes", sherbime:["zjarrfikes","policia","ambulance"],
        koha:"09:05", adresa:"Rr. Martirët Aliu nr.128, Milloshevë",
        pershkrimi:"Zjarr në magazinë karburanti pranë turbinës, rrezik shpërthimi, zonë evakuimi 500m",
        njesia:"Brigada Z-11 + Z-03 + Patrulla P-27 + Ambulanca A-02" },
      geometry:{ type:"Point", coordinates:[21.0712, 42.7092] } },

    { type:"Feature", properties:{ id:"INC005", lloji:"Aksident autobusi shkollor", ashpersia:"high", statusi:"aktiv",
        sherbimi:"policia", sherbime:["policia","ambulance","zjarrfikes"],
        koha:"08:55", adresa:"Rr. Momčila Sekulića nr.11, Graçanicë",
        pershkrimi:"Autobusi del nga rruga, 18 nxënës të lënduar, 2 rëndë, nevojiten shumë ambulanca",
        njesia:"Patrulla P-01 + P-24 + Ambulanca A-02 + A-50 + Brigada Z-11" },
      geometry:{ type:"Point", coordinates:[21.1968, 42.5998] } },

    { type:"Feature", properties:{ id:"INC006", lloji:"Rrjedhje kimike", ashpersia:"high", statusi:"aktiv",
        sherbimi:"zjarrfikes", sherbime:["zjarrfikes","ambulance","policia"],
        koha:"08:43", adresa:"Rr. Rozafa nr.1, Fushë Kosovë",
        pershkrimi:"Rrjedhje acidi industrial, 3 punëtorë me djegie kimike, evakuim i zonës 300m",
        njesia:"Brigada Z-11 + Z-03 + Ambulanca A-48 + Patrulla P-08" },
      geometry:{ type:"Point", coordinates:[21.0948, 42.6375] } },

    { type:"Feature", properties:{ id:"INC007", lloji:"Arrest kardiak", ashpersia:"high", statusi:"ne_trajtim",
        sherbimi:"ambulance", sherbime:["ambulance"],
        koha:"08:31", adresa:"Rr. Ibrahim Rugova, Gjilan",
        pershkrimi:"Mashkull 58 vjeç, arrest kardiak, i pa vetëdijshëm, RCP aktive nga ekipi mjekësor",
        njesia:"Ambulanca A-49" },
      geometry:{ type:"Point", coordinates:[21.4680, 42.4618] } },

    { type:"Feature", properties:{ id:"INC008", lloji:"Përplasje zinxhirore (5 vetura)", ashpersia:"high", statusi:"aktiv",
        sherbimi:"policia", sherbime:["policia","ambulance","zjarrfikes"],
        koha:"08:20", adresa:"Rr. 14 Prilli, Komuna e Drenasit",
        pershkrimi:"5 automjete të bllokuara, 1 veturë ka marrë flakë, 4 të lënduar, 1 kritik",
        njesia:"Patrulla P-09 + Brigada Z-03 + Ambulanca A-04" },
      geometry:{ type:"Point", coordinates:[20.8905, 42.6502] } },

    // ── ASHPËRSI MESATARE (MED) ──────────────────────────────────────────────────
    { type:"Feature", properties:{ id:"INC009", lloji:"Aksident rrugor — 2 vetura", ashpersia:"med", statusi:"aktiv",
        sherbimi:"policia", sherbime:["policia","ambulance"],
        koha:"08:08", adresa:"Rr. Deshtica, Romajë",
        pershkrimi:"Përplasje ballore, 2 të lënduar mesatarisht, rruga e ngushtë e bllokuar",
        njesia:"Patrulla P-11 + Ambulanca A-05" },
      geometry:{ type:"Point", coordinates:[20.5855, 42.2958] } },

    { type:"Feature", properties:{ id:"INC010", lloji:"Zjarr automjeti në lëvizje", ashpersia:"med", statusi:"aktiv",
        sherbimi:"zjarrfikes", sherbime:["zjarrfikes","policia"],
        koha:"07:55", adresa:"Rr. Rilindja Kombëtare nr.228, Gllanicë",
        pershkrimi:"Veturë kap flakë gjatë lëvizjes, shoferi evakuua i sigurt, rrezik përhapjeje",
        njesia:"Brigada Z-11 + Patrulla P-08" },
      geometry:{ type:"Point", coordinates:[21.0682, 42.5502] } },

    { type:"Feature", properties:{ id:"INC011", lloji:"Grabitje me dhunë", ashpersia:"med", statusi:"aktiv",
        sherbimi:"policia", sherbime:["policia"],
        koha:"07:42", adresa:"Rr. Shpetim Bojku, Pejë",
        pershkrimi:"2 persona me kapuç grabisin arkat e blerjes, arratisje me mjet motorik të vjedhur",
        njesia:"Patrulla P-05 + P-06" },
      geometry:{ type:"Point", coordinates:[20.2960, 42.6628] } },

    { type:"Feature", properties:{ id:"INC012", lloji:"Dhunë familjare me lëndime", ashpersia:"med", statusi:"aktiv",
        sherbimi:"policia", sherbime:["policia","ambulance"],
        koha:"07:30", adresa:"Rr. Emin Duraku nr.31, Ferizaj",
        pershkrimi:"Grua 34 vjeçe me lëndime në fytyrë dhe dorë, kërkohet ambulancë dhe ndërhyrje policore",
        njesia:"Patrulla P-23 + Ambulanca A-57" },
      geometry:{ type:"Point", coordinates:[21.1528, 42.3712] } },

    { type:"Feature", properties:{ id:"INC013", lloji:"Zjarr pyjor", ashpersia:"med", statusi:"aktiv",
        sherbimi:"zjarrfikes", sherbime:["zjarrfikes","policia"],
        koha:"07:18", adresa:"Rr. Rezistenca, Zym",
        pershkrimi:"Zjarr pyjor rreth 4 ha, erë e fortë jugore, përhapje e shpejtë, vështirësi aksesi",
        njesia:"Brigada Z-04 + Z-09 + Patrulla P-21" },
      geometry:{ type:"Point", coordinates:[20.6605, 42.1082] } },

    { type:"Feature", properties:{ id:"INC014", lloji:"Lëndim i rëndë në kantier ndërtimi", ashpersia:"med", statusi:"ne_trajtim",
        sherbimi:"ambulance", sherbime:["ambulance","policia"],
        koha:"06:55", adresa:"Rr. Dukagjin Vula, Matiqan",
        pershkrimi:"Punëtor bie nga skeleti, dyshohet frakturë vertebrore, imobilizim i nevojshëm",
        njesia:"Ambulanca A-02 + Patrulla P-03" },
      geometry:{ type:"Point", coordinates:[21.1832, 42.6532] } },

    { type:"Feature", properties:{ id:"INC015", lloji:"Aksident motoçikletë", ashpersia:"med", statusi:"aktiv",
        sherbimi:"policia", sherbime:["policia","ambulance"],
        koha:"06:40", adresa:"Rr. Ahmet Shala, Barilevë",
        pershkrimi:"Motoçikleta del nga rruga në kthesë, shoferi i lënduar me traumë koke, helmetë e thyer",
        njesia:"Patrulla P-32 + Ambulanca A-39" },
      geometry:{ type:"Point", coordinates:[21.1108, 42.7538] } },

    { type:"Feature", properties:{ id:"INC016", lloji:"Trazirë publike me dhunë", ashpersia:"med", statusi:"aktiv",
        sherbimi:"policia", sherbime:["policia"],
        koha:"06:25", adresa:"Rr. Ismail Qemajli nr.66, Vushtrri",
        pershkrimi:"Konflikt mes dy grupesh rreth 20 persona, dhunë fizike, 3 të lënduar lehtë, arrest",
        njesia:"Patrulla P-28 + njësi intervenimi" },
      geometry:{ type:"Point", coordinates:[20.9672, 42.8242] } },

    { type:"Feature", properties:{ id:"INC017", lloji:"Rrjedhje gazi LPG — banesë", ashpersia:"med", statusi:"aktiv",
        sherbimi:"zjarrfikes", sherbime:["zjarrfikes","ambulance"],
        koha:"06:10", adresa:"Lagja Jeni Mahalla, Prizren",
        pershkrimi:"Erë e fortë gazi LPG, ndërtesa dykatëshe, evakuim i banorëve, ndalim rrymës",
        njesia:"Brigada Z-09 + Ambulanca A-05" },
      geometry:{ type:"Point", coordinates:[20.7362, 42.2128] } },

    { type:"Feature", properties:{ id:"INC018", lloji:"Aksidenti i këmbësorit", ashpersia:"med", statusi:"ne_trajtim",
        sherbimi:"policia", sherbime:["policia","ambulance"],
        koha:"05:58", adresa:"Rr. Mbretëresha Teutë nr.122/2, Pejë",
        pershkrimi:"Veturë godet këmbësorin në kapërcyes, grua 45 vjeçe, frakturë e mundshme e pelvisit",
        njesia:"Patrulla P-05 + Ambulanca A-21" },
      geometry:{ type:"Point", coordinates:[20.2938, 42.6612] } },

    { type:"Feature", properties:{ id:"INC019", lloji:"Zjarr banesë dykatëshe", ashpersia:"med", statusi:"ne_trajtim",
        sherbimi:"zjarrfikes", sherbime:["zjarrfikes","ambulance"],
        koha:"05:45", adresa:"Rr. Muslim Mulliqi, Gjakovë",
        pershkrimi:"Zjarr nga shkëndija elektrike, kati i parë i djegur, 1 person me djegie të lehta",
        njesia:"Brigada Z-02 + Ambulanca A-13" },
      geometry:{ type:"Point", coordinates:[20.4408, 42.3762] } },

    // ── ASHPËRSI E ULËT (LOW) ────────────────────────────────────────────────────
    { type:"Feature", properties:{ id:"INC020", lloji:"Aksident i lehtë rrugor", ashpersia:"low", statusi:"aktiv",
        sherbimi:"policia", sherbime:["policia"],
        koha:"05:30", adresa:"Rr. Muhaxherët e Toplicës, Kçiq i Madh",
        pershkrimi:"2 vetura përplasje të lehta nga anash, pa të lënduar, trafik i ngadaltë",
        njesia:"Patrulla P-36" },
      geometry:{ type:"Point", coordinates:[20.9198, 42.8572] } },

    { type:"Feature", properties:{ id:"INC021", lloji:"Lëndim sportiv", ashpersia:"low", statusi:"ne_trajtim",
        sherbimi:"ambulance", sherbime:["ambulance"],
        koha:"05:12", adresa:"Rr. Jusuf Gërvalla, Prishtinë",
        pershkrimi:"Sportist 22 vjeç, frakturë e mundshme e kyçit të këmbës gjatë stërvitjes",
        njesia:"Ambulanca A-50" },
      geometry:{ type:"Point", coordinates:[21.1518, 42.6492] } },

    { type:"Feature", properties:{ id:"INC022", lloji:"Bllokadë rruge — aksidenti i lehtë", ashpersia:"low", statusi:"zgjidhur",
        sherbimi:"policia", sherbime:["policia"],
        koha:"04:55", adresa:"Rr. Iliria, Kamenicë",
        pershkrimi:"Veturë del nga rruga, rruga e bllokuar 45 min, trafik i ridrejtuar, pa të lënduar",
        njesia:"Patrulla P-26" },
      geometry:{ type:"Point", coordinates:[21.5795, 42.5822] } },

    { type:"Feature", properties:{ id:"INC023", lloji:"Zjarr i vogël automjeti", ashpersia:"low", statusi:"zgjidhur",
        sherbimi:"zjarrfikes", sherbime:["zjarrfikes"],
        koha:"04:40", adresa:"Rr. Edit Durham, Prizren",
        pershkrimi:"Motorçikleta merr flakë në parking (defekt elektrik), shuar shpejt, nuk përfshihen vetura tjera",
        njesia:"Brigada Z-09" },
      geometry:{ type:"Point", coordinates:[20.7398, 42.2172] } },

    { type:"Feature", properties:{ id:"INC024", lloji:"Rënie nga lartësia — lëndim i lehtë", ashpersia:"low", statusi:"ne_trajtim",
        sherbimi:"ambulance", sherbime:["ambulance"],
        koha:"04:22", adresa:"Rr. Aleksandër Stipçeviq, Prishtinë",
        pershkrimi:"Fëmijë 9 vjeç bie nga pajisja e lojërave, gju i mavijosur, pa frakturë",
        njesia:"Ambulanca A-03" },
      geometry:{ type:"Point", coordinates:[21.1628, 42.6592] } },

    { type:"Feature", properties:{ id:"INC025", lloji:"Kapje e personave të dyshimtë kufiri", ashpersia:"low", statusi:"zgjidhur",
        sherbimi:"policia", sherbime:["policia"],
        koha:"04:05", adresa:"Rr. Gryka e Llapit nr.1218, Podujevë",
        pershkrimi:"3 persona kapën duke kaluar ilegalisht kufirin, arrestuar, dërguar në qendër mbajtjeje",
        njesia:"Patrulla P-33" },
      geometry:{ type:"Point", coordinates:[21.2428, 42.9372] } },
  ]
};

// VGI Reports nga qytetarët
const VGI_REPORTS = [
  { id:"VGI001", lloji:"Bllokadë rrugore", adresa:"Rr. Murat Mehmeti, Prishtinë", lat:42.6700, lng:21.1598, koha:"09:51", statusi:"pa_verifikuar", pershkrimi:"Aksident i vogël bllokoi rrugën, trafik shumë i ngadaltë drejt qendrës", emri:"Arben M." },
  { id:"VGI002", lloji:"Tymë dyshues", adresa:"Rr. Adem Voca nr.24, Mitrovicë", lat:42.8885, lng:20.8648, koha:"09:33", statusi:"pa_verifikuar", pershkrimi:"Tymë e zezë vjen nga banesa e katit të dytë, banorët janë jashtë, asnjë njësi nuk ka ardhur akoma", emri:"Anonime" },
  { id:"VGI003", lloji:"Aksident rrugor", adresa:"Rr. Tivari, Gjilan", lat:42.4682, lng:21.4698, koha:"09:12", statusi:"konfirmuar", pershkrimi:"Veturë del nga rruga, godet barrierat, shoferi dukej i lënduar, ka shumë lëng mbi rrugë", emri:"Vjosa K." },
  { id:"VGI004", lloji:"Zjarr pyjor", adresa:"Rr. Fadil Latifi nr.49, Prekaz i Epërm", lat:42.7750, lng:20.8260, koha:"08:44", statusi:"pa_verifikuar", pershkrimi:"Shoh tym të madh nga pylli mbi fshat, flakë të dukshme, era e fut tymin drejt shtëpive", emri:"Muharrem B." },
  { id:"VGI005", lloji:"Rrugë e dëmtuar", adresa:"Rr. Rinia Shqipëtare, Greme", lat:42.3120, lng:21.1780, koha:"08:22", statusi:"pa_verifikuar", pershkrimi:"Gropa e madhe në mes të rrugës pas shirave të djeshëm, vetura po dëmtohen, nevojiten sinjale", emri:"Besim H." },
  { id:"VGI006", lloji:"Person i dyshimtë", adresa:"Rr. Beqir Kastrati, Pejë", lat:42.6615, lng:20.3058, koha:"07:58", statusi:"pa_verifikuar", pershkrimi:"Person i panjohur me qese të mëdha po vëren nga largësia hyrjen e shkollës prej 30 minutash", emri:"Miradije L." },
  { id:"VGI007", lloji:"Vërshim i vogël", adresa:"Rr. Selman Riza nr.47, Gjakovë", lat:42.3802, lng:20.4328, koha:"07:35", statusi:"konfirmuar", pershkrimi:"Nënkalimi i plotë me ujë nga shiu i natës, vetura ka mbetur e bllokuar, asnjë shenjë paralajmëruese", emri:"Liridon G." },
  { id:"VGI008", lloji:"Lëndim këmbësor", adresa:"Rr. Nijazi Gashi, Prizren", lat:42.2152, lng:20.7388, koha:"07:10", statusi:"pa_verifikuar", pershkrimi:"Grua e moshuar ka rënë mbi kalldrëm të lagësht, kërkon ndihmë, nuk mund të çohet", emri:"Fatmire S." },
];

// Zonat e rrezikut (GeoJSON Polygons)
const RISK_ZONES = {
  type: "FeatureCollection",
  features: [
    { type:"Feature", properties:{ lloji:"vershim", emri:"Zona vërshimit — Lumi Sitnica", rreziku:"i lartë" }, geometry:{ type:"Polygon", coordinates:[[[20.9,42.75],[21.0,42.75],[21.0,42.82],[20.9,42.82],[20.9,42.75]]] } },
    { type:"Feature", properties:{ lloji:"zjarr_pyjor", emri:"Zona rreziku zjarrit pyjor — Kaçanik", rreziku:"mesatar" }, geometry:{ type:"Polygon", coordinates:[[[21.2,42.22],[21.35,42.22],[21.35,42.32],[21.2,42.32],[21.2,42.22]]] } },
    { type:"Feature", properties:{ lloji:"rrëshqitje", emri:"Zona rrëshqitjes — Rugova", rreziku:"mesatar" }, geometry:{ type:"Polygon", coordinates:[[[20.05,42.65],[20.2,42.65],[20.2,42.73],[20.05,42.73],[20.05,42.65]]] } },
  ]
};
